user profile

diff --git a/80-cdn/Jenkinsfile b/80-cdn/Jenkinsfile
--- a/80-cdn/Jenkinsfile
+++ b/80-cdn/Jenkinsfile
@@ -79,13 +79,17 @@ pipeline {
             }
             steps{
                 withAWS(region: 'us-east-1', credentials: 'aws-creds') {
-                    sh """
-                    for i in 80-cdn 70-ecr 60-alb 50-acm 40-eks 20-bastion 10-sg 00-vpc
-                    do
-                        cd $i
-                        terraform destroy -auto-approve
-                    done
-                    """
+                    script {
+                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
+                        for (dir in directories) {
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                            cd ${dir}
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                            """
+                        }
+            }
                 }
             }
         }
